books/urls.py
from django.urls import path
from .views import IndexView, BookDetailView, GenreView, AddBookView, AddEditView
app_name='books'
urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('add/', AddBookView.as_view(), name="add"),
    path('g/<str:genre>', GenreView.as_view(), name="genre"),
    path('<slug:slug>/', BookDetailView.as_view(), name="book_detail"),
    path('<slug:slug>/edit', AddEditView.as_view(), name="edit_detail"),


]

cbv/urls.py
from django.urls import path
from cbv import views
from django.views.generic import TemplateView, RedirectView
urlpatterns=[
    path('', TemplateView.as_view(template_name="ex1.html", extra_context={'title':'custom title'}), name="ex1"), 
    path('ex2', views.Ex2View.as_view(), name="ex2"),
    path('rdt/', RedirectView.as_view(url="https://youtube.com/veryacademy"), name="go-to-very" ),
    path('ex3<str:pk>', views.PostPreLoadTaskView.as_view(), name="redirect_task" ),
    path('ex4/<str:pk>', views.SinglePostView.as_view(), name="singlepost"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('cbv.urls')),
    path('books/', include('books.urls'))

]

books/models.py
from django.db import models
from django.template.defaultfilters import slugify

# Create your models here.
class Book(models.Model):
    title =models.CharField(max_length=100)
    slug = models.SlugField(null=True)
    genre = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    isbn = models.IntegerField()
    count = models.IntegerField(null=True, default=0)


    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

cbv/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    name= models.CharField(max_length=100)
    count = models.IntegerField(null=True, default=0)

books/forms.py
from django import forms
from books.models import Book


class AddForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = {'title', 'genre', 'author', 'isbn'}

        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control'}),
            'genre':forms.TextInput(attrs={'class':'form-control'}),
            'author':forms.TextInput(attrs={'class':'form-control'}),
            'isbn':forms.TextInput(attrs={'class':'form-control'})
        }

books/views.py
from re import template
from django.shortcuts import render
from books.models import Book
from django.views.generic import TemplateView, DetailView, ListView, FormView, CreateView, UpdateView
from django.db.models import F
from django.utils import timezone
from books.forms import AddForm
# Create your views here.
class IndexView(ListView):
    model = Book
    template_name = 'home.html'
    context_object_name = 'books'
    paginate_by = 4

    # def get_queryset(self):
    #     return Book.objects.all()[:3]





class BookDetailView(DetailView):
    model = Book
    template_name = 'book_detail.html'
    context_object_name = 'book'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = Book.objects.filter(slug=self.kwargs.get('slug'))
        post.update(count=F('count')+1)
        context['time'] = timezone.now()
        return context

class GenreView(ListView):
    model=Book
    template_name="home.html"
    context_object_name = 'books'
    paginate_by = 2
    def get_queryset(self, *args, **kwargs):
        return Book.objects.filter(genre__icontains = self.kwargs.get('genre'))

# class AddBookView(FormView):
#     template_name='add.html'
#     form_class = AddForm
#     success_url = '/books/'

#     def form_valid(self, form):
#         form.save()
#         return super().form_valid(form)


class AddBookView(CreateView):
    model = Book
    template_name = 'add.html'
    success_url = '/books/'
    form_class = AddForm
    def get_initial(self, *args, **kwargs):
        initial = super().get_initial(**kwargs)
        initial['title'] = 'Enter Title'
        return initial

class AddEditView(UpdateView):
    model = Book
    template_name = 'add.html'
    form_class = AddForm
    success_url = '/books/'

cbv/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, RedirectView
from cbv.models import Post
from django.shortcuts import get_object_or_404
from django.db.models import F
# Create your views here.

class Ex2View(TemplateView):
    template_name = 'ex2.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.get(id=1)
        context['data'] = "context data for Ex2"
        return context

class PostPreLoadTaskView(RedirectView):
    pattern_name = 'singlepost'

    def get_redirect_url(self, *args, **kwargs):
        # post = get_object_or_404(Post, pk=kwargs['pk'])
        # post.count = f('count') +1
        # post.save()

        post = Post.objects.filter(pk=kwargs['pk'])
        post.update(count=F('count') + 1)

        return super().get_redirect_url(*args, **kwargs)
    

class SinglePostView(TemplateView):
    template_name = 'ex4.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = get_object_or_404(Post, pk=self.kwargs.get('pk'))
        return context

books/templates/add.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1 class="my-4 text-center">Books</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit">
    </form>
</div>
{% endblock %}

books/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{%block title%} Welcome to books{%endblock %}</title>
  </head>
  <body>
    {% block content %}
    
    {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

books/templates/book_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container" sytle="max-width:800px">
    <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">{{book.title}}</h1>
        <div class="d-flex justify-content-between align-items-center">
            <small class="text-muted">{{book.genre}}</small>
            <small class="text-muted">{{book.isbn}}</small>
            <small class="text-muted">{{time}}</small>
        </div>
    </div>
</div>
{% endblock %}

books/templates/home.html
{% extends 'base.html' %}
{% block content %}
{% comment %} {% for book in books %}
{{book.title}}
{% endfor %} {% endcomment %}
<h1 class="text-center">All Books</h1>
    {% for book in books %}
        <div class="container my-4">
            <a href="{%url 'books:book_detail' slug=book.slug %}">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">{{book.title|truncatechars:10}}</h5>
                        <a href="#" class="card-link">{{book.genre}}</a>
                        <a href="#" class="card-link">{{book.isbn}}</a>
                    </div>
                    </div>
                </div>
            </a>
        </div>
    {% endfor %}
    <div class=row>
        <div class="col-12">
            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
            
                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
            
                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">next</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
{% endblock %}

templates/ex1.html
//Homepage
<hr>
{{title}}

templates/ex2.html
//Example 2
<hr/>
<a href="{%url 'go-to-very'%}">Very Academy School</a>
<hr/>
{{data}}
<hr>
{{posts.name}}
<hr>
<a href="{%url 'redirect_task' pk=posts.id %}">{{posts.name}}</a>

templates/ex4.html
<hr>
{{posts.name}}